
var ZONE_LOOKUP = {
    1: { zone: 'Newark Airport', borough: 'EWR' },
    2: { zone: 'Astoria', borough: 'Queens' },
    3: { zone: 'Allerton/Pelham Gardens', borough: 'Bronx' },
    4: { zone: 'Alphabet City', borough: 'Manhattan' },
    5: { zone: 'Arden Heights', borough: 'Staten Island' },
    6: { zone: 'Arrochar/Fort Wadsworth', borough: 'Staten Island' },
    7: { zone: 'Astoria Park', borough: 'Queens' },
    11: { zone: 'Bath Beach', borough: 'Brooklyn' },
    12: { zone: 'Battery Park', borough: 'Manhattan' },
    13: { zone: 'Battery Park City', borough: 'Manhattan' },
    14: { zone: 'Bay Ridge', borough: 'Brooklyn' },
    22: { zone: 'Bedford-Stuyvesant', borough: 'Brooklyn' },
    43: { zone: 'Central Park', borough: 'Manhattan' },
    45: { zone: 'Chinatown', borough: 'Manhattan' },
    65: { zone: 'Downtown Brooklyn/MetroTech', borough: 'Brooklyn' },
    82: { zone: 'Flushing', borough: 'Queens' },
    101: { zone: 'Jamaica', borough: 'Queens' },
    130: { zone: 'JFK Airport', borough: 'Queens' },
    134: { zone: 'LaGuardia Airport', borough: 'Queens' },
    138: { zone: 'Long Island City/Hunters Point', borough: 'Queens' },
    161: { zone: 'Midtown Center', borough: 'Manhattan' },
    162: { zone: 'Midtown East', borough: 'Manhattan' },
    163: { zone: 'Midtown North', borough: 'Manhattan' },
    164: { zone: 'Midtown South', borough: 'Manhattan' },
    224: { zone: 'Times Sq/Theatre District', borough: 'Manhattan' },
    236: { zone: 'Upper West Side North', borough: 'Manhattan' },
    237: { zone: 'Upper West Side South', borough: 'Manhattan' }
};
